### ISSUE TITLE
Add filter to allow certain users to have concurrent sessions when necessary

### ISSUE THREAD

**Issue by frankiejarrett** [fjarrett/prevent-concurrent-logins#1]
This suggestion was proposed by @nutsandbolts:

> After trying out the plugin, my only suggestion would be to have the option to allow concurrent logins for administrators. I often switch between my laptop and desktop when working on my own sites, and having to log in over and over is driving me crazy.

**Comment by frankiejarrett** [comment]
@nutsandbolts This can now be done by adding this to your theme's `functions.php` or as an MU plugin:

``` php
function fjarrett_pcl_bypass_admins( $user_id ) {
    $user = get_user_by( 'id', absint( $user_id ) );

    if ( ! empty( $user->roles[0] ) && 'administrator' === $user->roles[0] ) {
        return false;
    }

    return true;
}
add_filter( 'pcl_prevent_concurrent_logins', 'fjarrett_pcl_bypass_admins', 10, 1 );
```

**Comment by nutsandbolts** [comment]
@fjarrett Thanks - that was some quick work! Appreciate it. :)
