### ISSUE TITLE
Logout and login page for users on normal pages

### ISSUE THREAD

**Issue by MarekAdam** [fjarrett/prevent-concurrent-logins#12]
When there is automatic logout login page shown. But only on admin pages. I have wocommerce subscription webpage and want to logout user on open normal pages too. Can i do that?

**Comment by frankiejarrett** [comment]
This plugin doesn't control UI or redirect to certain pages, it simply manages/destroys the WP sessions for users. For this you should consider something like https://wordpress.org/plugins/peters-login-redirect/
