### ISSUE TITLE
Destroy all old user sessions on plugin activation

### ISSUE THREAD

**Issue by frankiejarrett** [fjarrett/prevent-concurrent-logins#2]
Currently, old sessions for users are only destroyed when users login, they are not destroyed automatically when the plugin is activated because the code is designed to affect `$current_user` only.

This would be a nice feature to add so that immediate results are seen instead of having to wait for every user to take action. Even with several tens of thousands of users the process should be lean enough to run in only a few seconds.

See this comment by @chuckreynolds in a related project: https://github.com/fjarrett/user-session-control/issues/2#issuecomment-71761349

**Comment by frankiejarrett** [comment]
@chuckreynolds I've just released `0.2.0` that will destroy old sessions upon activation.

This will ensure that the total number of sessions always matches the total number of unique users logged in from the start of using the plugin.

https://wordpress.org/plugins/prevent-concurrent-logins/changelog/

**Comment by chuckreynolds** [comment]
@fjarrett nice. for that site it removed about 500 of them.
