### ISSUE TITLE
Logging destroys

### ISSUE THREAD

**Issue by szepeviktor** [fjarrett/prevent-concurrent-logins#4]
Could you add two hooks here to provide logging?
https://github.com/fjarrett/prevent-concurrent-logins/blob/master/prevent-concurrent-logins.php#L68-L72
One for `destroy_other` and `destroy_current`.

**Comment by szepeviktor** [comment]
With the user name (or ID) as the only parameter.

**Comment by szepeviktor** [comment]
Of course **after** distroy.

**Comment by frankiejarrett** [comment]
@szepeviktor Great idea, I'll add that.

**Comment by szepeviktor** [comment]
Thank you.
I've discovered the proposed feature in the changelog.

**Comment by frankiejarrett** [comment]
You're very welcome @szepeviktor! Thanks again for the excellent suggestion.
