### ISSUE TITLE
breaks cross site authentication

### ISSUE THREAD

**Issue by n0risc** [fjarrett/prevent-concurrent-logins#5]
Without this plugin visiting other sites authentication is automatic. Meaning, it is not required to login to each individual blog on a multi-site installation. 

With this plugin, visiting other sites, authentication doesn't occur. Meaning, it is required to login to each individual blog on a multi-site installation. This action logs you out of all other blogs in the process, dooming the ability to authenticate once for the entire network.

**Comment by frankiejarrett** [comment]
Thanks for the report. I will try to reproduce this myself.

**Comment by frankiejarrett** [comment]
Hey @n0risc, so far I cannot replicate this using a sub-directory multisite installation of 4.4-alpha. The plugin seems to be working as expected and cross-site auth is being maintained.

Can you provide me with some more details about your environment?
- WordPress multisite version
- Is it a sub-domain or sub-directory multisite install?
- Is the plugin Network Activated or just active on certain sites?
- Are you using any custom domain mapping?

**Comment by n0risc** [comment]
Wordpress 4.3.1
sub-directory
it is network-activated, along side the proper network activation as required.

Additional plugins installed: 
Multi-Site User Management plugin -- new users are added to each multi-site with appropriate roles
WordPress MU Domain Mapping -- which redirects FQDN's to the respective subdomain url

**Comment by n0risc** [comment]
Hey @fjarrett. I leaning towards the Wordpress MU Domain Mapping plugin that is causing this plugin to not work as intended. If I stay away from the mapped domain, switching from site to site, and back to dashboards works fine. But as soon as I hit the site with the mapped domain it logs me out and then accessing the dashboard, it asks for username/password again.

I also had to tick.  disable primary domain checking in the Wordpress MU Domain Mapping Plugin, for it not to redirect to the domain, so I can access the sub directory url.

This may be because the 'init' hook that is being used to do the action of destroying other sessions, is being called again for whatever reason.

**Comment by frankiejarrett** [comment]
@n0risc could it be because the custom domains are used in auth cookies? Perhaps user sessions in WordPress don't play nice with multiple TLD's on the same network.

**Comment by n0risc** [comment]
@fjarrett Maybe. But there's a pretty extensive code written in the domain_mapping.php of the MU Mapping Domain Plugin which should extend the auth to the TLD redirect. Or the lack thereof.
