### ISSUE TITLE
multisite super-admin locked out

### ISSUE THREAD

**Issue by n0risc** [fjarrett/prevent-concurrent-logins#6]
when logging in as super-admin on main blog or any blog in multi-site installation causes a re-direct loop with these url arguments   http://example.com?redirect_to=http%3A%2F%2Fexample.com%2Fwp-admin%2F&reauth=1

**Comment by frankiejarrett** [comment]
Thanks! I will try to reproduce.

**Comment by n0risc** [comment]
Solved issue by using the already supplied filter function my_pcl_bypass_user_ids, and adding the appropriate super admin user id.

**Comment by frankiejarrett** [comment]
Thanks @n0risc. I believe that this issue, as well as #5, are only happening on specific types of environments. When testing on a sub-directory multisite installation on 4.4-alpha I am not able to reproduce.

I'm taking a wild guess that these issues are only happening on sub-domain multisite installs and/or installs with custom domain mapping. So I guess the next step here is to confirm if my assumption is right.

**Comment by n0risc** [comment]
You're welcome @fjarrett . I've also assumed another issue is the MU Multisite Domain Mapping Plugin is causing the additional execution of the 'init' hook for whatever reason when mapping the sites subdirectory url to the primary domain, and the checking of it. I have disabled the primary domain checking in the MU Multisite Domain Mapping Plugin which helps keep the authentication alive switching between sites and dashboards, but as soon as I use the mapped domain name, PWOOF, the authentication is destroyed. The only reason has to be the 'init' hook is being called again in this process of domain mapping. More probable the redirection code.
