### ISSUE TITLE
Restrict to IP

### ISSUE THREAD

**Issue by szepeviktor** [fjarrett/prevent-concurrent-logins#8]
@fjarrett Do have an idea how to restrict WP sessions to the initial (at login time) IP address?
I'd like to implement it.

**Comment by frankiejarrett** [comment]
@szepeviktor That sounds kind of scary. I believe if you have valid credentials you should never be locked out of your account, with maybe the exception of a fail2ban on a known brute force attack or something. Maybe I'm misunderstanding your idea?

The purpose of the plugin has always been to honor the most recent session for a user and to invalidate the old sessions. I think the name of my plugin is misleading because I get this question a lot. Maybe a better name would have been something like **Destroy Old Sessions**.

**Comment by szepeviktor** [comment]
> That sounds kind of scary.

Yes. Providing you have unknown users.
I only have known users with phone&Skype contact. So I like when they call me.

Could you give me an advise which WP filter to use to achieve IP address locking? (outside of this plugin)

**Comment by frankiejarrett** [comment]
@szepeviktor Cool. Well there isn't a filter AFAIK. The only way I know to get the current session is seen in this plugin here: https://github.com/fjarrett/prevent-concurrent-logins/blob/1bf4c30227076c41d1021a9fd6331d10c79430d5/prevent-concurrent-logins.php#L28-L39

The IP is inside the session array, so you could define an array of known/allowed IPs, and just call `wp_destroy_current_session()` on `init` if someone logs in from an unknown IP.

**Comment by szepeviktor** [comment]
Thank you.
~~Before~~ After making it an MU plugin:

``` php
/**
 * Inspect IP address after default authentication filters.
 */
add_filter( 'determine_current_user', 'o1_check_session_ip', 30 );

/**
 * Compare IP in session and destroy session on mismatch.
 */
function o1_check_session_ip( $user_id ) {

    if ( false !== $user_id ) {

        $sessions = WP_Session_Tokens::get_instance( $user_id );
        $session = $sessions->get( wp_get_session_token() );
        if ( empty( $session )
            || empty( $session['ip'] )
            || empty( $_SERVER['REMOTE_ADDR'] )
            || $session['ip'] !== $_SERVER['REMOTE_ADDR']
        ) {
            // User's IP address has changed, log him out
            add_action( 'init', 'wp_destroy_current_session', 0 );
            error_log( 'Destroy session for user #' . $user_id );
        }
    }

    return $user_id;
}
```

**Comment by szepeviktor** [comment]
> so you could define an array of known/allowed IPs

I think I was not clear enough.
I'd like to stick to the lP at login time.

Thank you very much for your help.
